-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2025-08-13 16:11:48 COT
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE AUTENTICACION 
    ( 
     AUTE_ID            NUMBER (30)  NOT NULL , 
     USUA_ID            NUMBER (30)  NOT NULL , 
     TIAU_ID            NUMBER (30)  NOT NULL , 
     AUTE_HASH          VARCHAR2 (255) , 
     AUTE_IDENTIFICADOR VARCHAR2 (50) , 
     AUTE_ESTADO        NUMBER , 
     AUTE_FECHACAMBIO   TIMESTAMP , 
     AUTE_REGISTRADOPOR VARCHAR2 (30) 
    ) 
;

ALTER TABLE AUTENTICACION 
    ADD CONSTRAINT AUTENTICACION_PK PRIMARY KEY ( AUTE_ID ) ;

CREATE TABLE CIUDAD 
    ( 
     CIUD_ID             NUMBER (30)  NOT NULL , 
     REGI_ID             NUMBER (30)  NOT NULL , 
     ZOHO_ID             NUMBER (30)  NOT NULL , 
     CIUD_NOMBRE         VARCHAR2 (300)  NOT NULL , 
     CIUD_CODIGODANE     VARCHAR2 (10)  NOT NULL , 
     CIUD_CODIGOPOSTAL   VARCHAR2 (10)  NOT NULL , 
     CIUD_ESTADO         NUMBER  NOT NULL , 
     CIUD_RESGISTRADOPOR VARCHAR2 (30) , 
     CIUD_FECHACAMBIO    TIMESTAMP 
    ) 
;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT CIUDAD_PK PRIMARY KEY ( CIUD_ID ) ;

CREATE TABLE CUENTAVENTA 
    ( 
     CUVE_ID            NUMBER (30)  NOT NULL , 
     VENT_ID            NUMBER (30)  NOT NULL , 
     CUEV_NUMERO        NUMBER (3)  NOT NULL , 
     CUEV_TOTAL         NUMBER (20)  NOT NULL , 
     CUEV_PROPINA       NUMBER (20)  NOT NULL , 
     CUEV_ESTADO        NUMBER  NOT NULL , 
     CUEV_REGISTRADOPOR VARCHAR2 (30) , 
     CUEV_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE CUENTAVENTA 
    ADD CONSTRAINT CUENTAVENTA_PK PRIMARY KEY ( CUVE_ID ) ;

CREATE TABLE "DETALLECUENTAVENTA " 
    ( 
     DECV_ID            NUMBER (30)  NOT NULL , 
     CUVE_ID            NUMBER (30)  NOT NULL , 
     PREC_ID            NUMBER (30)  NOT NULL , 
     DECV_CANTIDAD      NUMBER (10)  NOT NULL , 
     DECV_SUBTOTAL      NUMBER (20)  NOT NULL , 
     DECV_FECHACAMBIO   DATE , 
     DECV_REGISTRADOPOR VARCHAR2 (30) 
    ) 
;

ALTER TABLE "DETALLECUENTAVENTA " 
    ADD CONSTRAINT DETALLEVENTA_PK PRIMARY KEY ( DECV_ID ) ;

CREATE TABLE EMPRESA 
    ( 
     EMPR_ID                NUMBER (30)  NOT NULL , 
     TIID_ID                NUMBER (30)  NOT NULL , 
     PAIS_IDTELEFONO        NUMBER (30)  NOT NULL , 
     CIUD_ID                NUMBER (30)  NOT NULL , 
     ZOHO_ID                NUMBER (30)  NOT NULL , 
     EMPRE_NOMBRECOMERCIAL  VARCHAR2 (100)  NOT NULL , 
     EMPR_RAZONSOCIAL       VARCHAR2 (300)  NOT NULL , 
     EMPR_IDENTIFICACION    VARCHAR2 (20)  NOT NULL , 
     EMPR_DIRECCION         VARCHAR2 (100)  NOT NULL , 
     EMPR_CODIGOPOSTAL      VARCHAR2 (30) , 
     EMPR_TELEFONO          VARCHAR2 (15)  NOT NULL , 
     EMPR_CORREOELECTRONICO VARCHAR2 (200)  NOT NULL , 
     EMPR_SITIOWEB          VARCHAR2 (300) , 
     EMPR_LOGO              VARCHAR2 (500) , 
     EMPR_ESTADO            NUMBER  NOT NULL , 
     EMPR_REGISTRADOPOR     VARCHAR2 (30) , 
     EMPR_FECHACAMBIO       TIMESTAMP 
    ) 
;

ALTER TABLE EMPRESA 
    ADD CONSTRAINT EMPRESA_PK PRIMARY KEY ( EMPR_ID ) ;

CREATE TABLE INVENTARIO 
    ( 
     INVT_ID            NUMBER (30)  NOT NULL , 
     PROD_ID            NUMBER (30)  NOT NULL , 
     SUCU_ID            NUMBER (30)  NOT NULL , 
     INVT_CANTIDAD      NUMBER (30)  NOT NULL , 
     INVT_FECHA         TIMESTAMP  NOT NULL , 
     INVT_REGISTRADOPOR VARCHAR2 (30) , 
     INVT_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE INVENTARIO 
    ADD CONSTRAINT INVENTARIO_PK PRIMARY KEY ( INVT_ID ) ;

CREATE TABLE LOG_CREDENCIAL 
    ( 
     LGCR_ID            NUMBER (30)  NOT NULL , 
     USUA_ID            NUMBER (30)  NOT NULL , 
     TIAU_ID            NUMBER (30)  NOT NULL , 
     AUTE_HASH          VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
                    , 
     AUTE_IDENTIFICADOR VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
                    , 
     LGCR_REGISTRADOPOR TIMESTAMP , 
     LGCR_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE LOG_CREDENCIAL 
    ADD CONSTRAINT LOG_CREDENCIAL_PK PRIMARY KEY ( LGCR_ID ) ;

CREATE TABLE LOGIN_LOG 
    ( 
     LOGI_ID            NUMBER (30)  NOT NULL , 
     USUA_ID            NUMBER (30)  NOT NULL , 
     LOGI_TIPO          VARCHAR2 (10)  NOT NULL , 
     LOGI_FECHA         TIMESTAMP  NOT NULL , 
     LOGI_REGISTRADOPOR VARCHAR2 (30) , 
     LOGI_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE LOGIN_LOG 
    ADD CONSTRAINT LOGIN_LOG_PK PRIMARY KEY ( LOGI_ID ) ;

CREATE TABLE MARCA 
    ( 
     MRCA_ID             NUMBER (30)  NOT NULL , 
     MRCA_NOMBRE         VARCHAR2 (30)  NOT NULL , 
     MRCA_IDENTIFICACION VARCHAR2 (50) , 
     MRCA_LOGO           BLOB , 
     MRCA_CREADOPOR      VARCHAR2 (30) , 
     MRCA_FECHACAMBIO    TIMESTAMP 
    ) 
;
CREATE INDEX MARCA__IDX ON MARCA 
    ( 
     MRCA_ID ASC 
    ) 
;

ALTER TABLE MARCA 
    ADD CONSTRAINT MARCA_PK PRIMARY KEY ( MRCA_ID ) ;

CREATE TABLE MEDIOPAGO 
    ( 
     MEPA_ID            NUMBER (30)  NOT NULL , 
     MEPA_NOMBRE        VARCHAR2 (20)  NOT NULL , 
     MEPA_DESCRIPCION   VARCHAR2 (50)  NOT NULL , 
     MEPA_ESTADO        NUMBER  NOT NULL , 
     MEPA_REGISTRADOPOR VARCHAR2 (30) , 
     MEPA_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE MEDIOPAGO 
    ADD CONSTRAINT MEDIOPAGO_PK PRIMARY KEY ( MEPA_ID ) ;

CREATE TABLE MENUS 
    ( 
     MENU_ID            NUMBER (30)  NOT NULL , 
     MENU_NOMBRE        VARCHAR2 (50)  NOT NULL , 
     MENU_DESCRIPCION   VARCHAR2 (100)  NOT NULL , 
     MENU_PARAMETRO     VARCHAR2 (50)  NOT NULL , 
     MENU_REGISTARDOPOR VARCHAR2 (30) , 
     MENU_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE MENUS 
    ADD CONSTRAINT MENUS_PK PRIMARY KEY ( MENU_ID ) ;

CREATE TABLE MESA 
    ( 
     MESA_ID            NUMBER (30)  NOT NULL , 
     SUCU_ID            NUMBER (30)  NOT NULL , 
     MESA_NUMERO        NUMBER (10)  NOT NULL , 
     MESA_ESTADO        VARCHAR2 (20)  NOT NULL , 
     MESA_REGISTRADOPOR VARCHAR2 (3O) , 
     MESA_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE MESA 
    ADD CONSTRAINT MESA_PK PRIMARY KEY ( MESA_ID ) ;

CREATE TABLE MONEDA 
    ( 
     MONE_ID            NUMBER (30)  NOT NULL , 
     MONE_CODIGOISO     VARCHAR2 (10)  NOT NULL , 
     MONE_NOMBRE        VARCHAR2 (50)  NOT NULL , 
     MONE_SIMBOLO       VARCHAR2 (1)  NOT NULL , 
     MONE_DECIMALES     NUMBER (2)  NOT NULL , 
     MONE_ESTADO        NUMBER  NOT NULL , 
     MONE_REGISTRADOPOR NUMBER (30) , 
     MONE_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE MONEDA 
    ADD CONSTRAINT MONEDA_PK PRIMARY KEY ( MONE_ID ) ;

CREATE TABLE MOVIMIENTOS 
    ( 
     MOVI_ID            NUMBER (30)  NOT NULL , 
     PROD_ID            NUMBER (30)  NOT NULL , 
     SUCU_ID            NUMBER (30)  NOT NULL , 
     TIMO_ID            NUMBER (30)  NOT NULL , 
     MOVI_CANTIDAD      NUMBER (10)  NOT NULL , 
     MOVI_MOTIVO        VARCHAR2 (100)  NOT NULL , 
     MOVI_REFERENCIA    VARCHAR2 (300)  NOT NULL , 
     MOVI_REGISTRADOPOR VARCHAR2 (30) , 
     MOVI_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE MOVIMIENTOS 
    ADD CONSTRAINT MOVIMIENTOS_PK PRIMARY KEY ( MOVI_ID ) ;

CREATE TABLE OPCIONMENU 
    ( 
     OPME_ID               NUMBER (30)  NOT NULL , 
     MENU_ID               NUMBER (30)  NOT NULL , 
     ROLE_ID               NUMBER (30)  NOT NULL , 
     OPME_NOMBRE           VARCHAR2 (50)  NOT NULL , 
     OPME_DESCRIPCION      VARCHAR2 (100)  NOT NULL , 
     OPME_CODIGOTRADUCCION VARCHAR2 (10)  NOT NULL , 
     OPME_REGISTRADOPOR    VARCHAR2 (30) , 
     OPME_FECHACAMBIO      TIMESTAMP 
    ) 
;

ALTER TABLE OPCIONMENU 
    ADD CONSTRAINT OPCIONMENU_PK PRIMARY KEY ( OPME_ID ) ;

CREATE TABLE PAGOCUENTAVENTA 
    ( 
     PACV_ID            NUMBER (30)  NOT NULL , 
     CUVE_ID            NUMBER (30)  NOT NULL , 
     MEPA_ID            NUMBER (30)  NOT NULL , 
     PACV_MONTO         NUMBER (20)  NOT NULL , 
     PACV_OBSERVACION   NUMBER (30) , 
     PACV_REGISTRADOPOR VARCHAR2 (30) , 
     PACV_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE PAGOCUENTAVENTA 
    ADD CONSTRAINT PAGOCUENTAVENTA_PK PRIMARY KEY ( PACV_ID ) ;

CREATE TABLE PAIS 
    ( 
     PAIS_ID            NUMBER (30)  NOT NULL , 
     ZOHO_ID            NUMBER (30)  NOT NULL , 
     PAIS_NOMBRE        VARCHAR2 (30)  NOT NULL , 
     PAIS_CODIGO        VARCHAR2 (20)  NOT NULL , 
     PAIS_ESTADO        NUMBER  NOT NULL , 
     PAIS_REGISTRADOPOR VARCHAR2 (30) , 
     PAIS_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE PAIS 
    ADD CONSTRAINT PAIS_PK PRIMARY KEY ( PAIS_ID ) ;

CREATE TABLE PARAMETROS 
    
    -- No Columns 
    
;

CREATE TABLE PRECIO 
    ( 
     PREC_ID            NUMBER (30)  NOT NULL , 
     PROD_ID            NUMBER (30)  NOT NULL , 
     SUCU_ID            NUMBER (30)  NOT NULL , 
     PREC_ESTADO        NUMBER (1)  NOT NULL , 
     PREC_VALORVENTA    NUMBER (15)  NOT NULL , 
     PREC_VALORCOMPRA   NUMBER (15)  NOT NULL , 
     PREC_FECHAINICIA   TIMESTAMP  NOT NULL , 
     PREC_FECHAFINALIZA TIMESTAMP , 
     PREC_REGISTRADOPOR VARCHAR2 (30) , 
     PREC_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE PRECIO 
    ADD CONSTRAINT PRECIO_PK PRIMARY KEY ( PREC_ID ) ;

CREATE TABLE PRODUCTOS 
    ( 
     PROD_ID          NUMBER (30)  NOT NULL , 
     SUCU_ID          NUMBER (30)  NOT NULL , 
     TPPR_ID          NUMBER (30)  NOT NULL , 
     MRCA_ID          NUMBER (30)  NOT NULL , 
     PROD_NOMBRE      VARCHAR2 (30)  NOT NULL , 
     PROD_DESCRIPCION VARCHAR2 (400)  NOT NULL , 
     PROD_CREADOPOR   VARCHAR2 (30) , 
     PROD_FECHACAMBIO TIMESTAMP 
    ) 
;
CREATE INDEX PRODUCTOS__IDX ON PRODUCTOS 
    ( 
     PROD_ID ASC 
    ) 
;

ALTER TABLE PRODUCTOS 
    ADD CONSTRAINT PRODUCTOS_PK PRIMARY KEY ( PROD_ID, SUCU_ID ) ;

CREATE TABLE REGION 
    ( 
     REGI_ID            NUMBER (30)  NOT NULL , 
     PAIS_ID            NUMBER (30)  NOT NULL , 
     ZOHO_ID            NUMBER (30)  NOT NULL , 
     REGI_NOMBRE        VARCHAR2 (30)  NOT NULL , 
     REGI_CODIGO        VARCHAR2 (10)  NOT NULL , 
     REGI_ESTADO        NUMBER , 
     REGI_REGISTRADOPOR VARCHAR2 (30) , 
     REGI_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE REGION 
    ADD CONSTRAINT REGION_PK PRIMARY KEY ( REGI_ID ) ;

CREATE TABLE ROLES 
    ( 
     ROLE_ID            NUMBER (30)  NOT NULL , 
     TIUS_ID            NUMBER (30)  NOT NULL , 
     ROLE_NOMBRE        VARCHAR2 (50)  NOT NULL , 
     ROLE_DESCRIPCION   VARCHAR2 (100)  NOT NULL , 
     ROLE_REGISTRADOPOR VARCHAR2 (30) , 
     ROLE_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE ROLES 
    ADD CONSTRAINT ROLES_PK PRIMARY KEY ( ROLE_ID ) ;

CREATE TABLE SUCURSAL 
    ( 
     SUCU_ID            NUMBER (30)  NOT NULL , 
     EMPR_ID            NUMBER (30)  NOT NULL , 
     CIUD_ID            NUMBER (30)  NOT NULL , 
     ZOHO_ID            NUMBER (30)  NOT NULL , 
     MONE_ID            NUMBER (30)  NOT NULL , 
     PAIS_IDTELEFONO    NUMBER (30)  NOT NULL , 
     SUCU_NOMBRE        VARCHAR2 (100)  NOT NULL , 
     SUCU_CODIGOINTERNO VARCHAR2 (50)  NOT NULL , 
     SUCU_DIRECCION     VARCHAR2 (25)  NOT NULL , 
     SUCU_TELEFONO      VARCHAR2 (20)  NOT NULL , 
     SUCU_ESTADO        NUMBER  NOT NULL , 
     SUCU_REGISTRADOPOR VARCHAR2 (30) , 
     SUCU_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_PK PRIMARY KEY ( SUCU_ID ) ;

CREATE TABLE TIPO_IDENTIFICACION 
    ( 
     TIID_ID            NUMBER (30)  NOT NULL , 
     TIID_NOMBRE        VARCHAR2 (50)  NOT NULL , 
     TIID_DESCRIPCION   VARCHAR2 (100)  NOT NULL , 
     TIID_ESTADO        NUMBER  NOT NULL , 
     TIID_REGISTRADOPOR VARCHAR2 (30) , 
     TIID_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE TIPO_IDENTIFICACION 
    ADD CONSTRAINT TIPOIDENTIFICACION_PK PRIMARY KEY ( TIID_ID ) ;

CREATE TABLE TIPO_PRODUCTOS 
    ( 
     TPPR_ID            NUMBER (30)  NOT NULL , 
     TPPR_NOMBRE        VARCHAR2 (30)  NOT NULL , 
     TPPR_DESCRIPCION   VARCHAR2 (300)  NOT NULL , 
     TPPR_CREADOPOR     VARCHAR2 (30) , 
     TPPR_FECHACREACION TIMESTAMP 
    ) 
;
CREATE INDEX TIPO_PRODUCTOS__IDX ON TIPO_PRODUCTOS 
    ( 
     TPPR_ID ASC 
    ) 
;

ALTER TABLE TIPO_PRODUCTOS 
    ADD CONSTRAINT TIPO_PRODUCTOS_PK PRIMARY KEY ( TPPR_ID ) ;

CREATE TABLE TIPOAUTENTICACION 
    ( 
     TIAU_ID            NUMBER (30)  NOT NULL , 
     TIAU_NOMBRE        VARCHAR2 (30)  NOT NULL , 
     TIAUD_TOKEN        VARCHAR2 (300) , 
     TIAU_DESCRIPCION   VARCHAR2 (50) , 
     TIAU_REGISTRADOPOR VARCHAR2 (30) , 
     TIAU_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE TIPOAUTENTICACION 
    ADD CONSTRAINT TIPOAUTENTICACION_PK PRIMARY KEY ( TIAU_ID ) ;

CREATE TABLE TIPOMOVIMIENTO 
    ( 
     TIMO_ID            NUMBER (30)  NOT NULL , 
     TIMO_NOMBRE        VARCHAR2 (50)  NOT NULL , 
     TIMO_DESCRIPCION   VARCHAR2 (100)  NOT NULL , 
     TIMO_REGISTRADOPOR VARCHAR2 (30) , 
     TIMO_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE TIPOMOVIMIENTO 
    ADD CONSTRAINT TIPOMOVIMIENTO_PK PRIMARY KEY ( TIMO_ID ) ;

CREATE TABLE TIPOUSUARIO 
    ( 
     TIUS_ID            NUMBER (30)  NOT NULL , 
     TIUS_NOMBRE        VARCHAR2 (50)  NOT NULL , 
     TIUS_DESCRIPCION   VARCHAR2 (100)  NOT NULL , 
     TIUS_ESTADO        NUMBER  NOT NULL , 
     TIUS_REGISTRADOPOR VARCHAR2 (30) , 
     TIUS_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE TIPOUSUARIO 
    ADD CONSTRAINT TIPOUSUARIO_PK PRIMARY KEY ( TIUS_ID ) ;

CREATE TABLE USUARIOROL 
    ( 
     USRO_ID            NUMBER (30)  NOT NULL , 
     USUA_ID            NUMBER (30)  NOT NULL , 
     ROLE_ID            NUMBER (30)  NOT NULL , 
     USRO_REGISTRADOPOR VARCHAR2 (30) , 
     USRO_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE USUARIOROL 
    ADD CONSTRAINT MENUUSUARIO_PK PRIMARY KEY ( USRO_ID ) ;

CREATE TABLE USUARIOS 
    ( 
     USUA_ID                 NUMBER (30)  NOT NULL , 
     CIUD_ID                 NUMBER (30)  NOT NULL , 
     EMPR_ID                 NUMBER (30)  NOT NULL , 
     USUA_ESTADO             NUMBER , 
     USUA_BLOQUEADO          NUMBER , 
     USUA_PRIMERNOMBRE       VARCHAR2 (20)  NOT NULL , 
     USUA_SEGUNDONOMBRE      VARCHAR2 (20) , 
     USUA_SEGUNDOAPELLIDO    VARCHAR2 (20)  NOT NULL , 
     USUA_PRIMERAPELLIDO     VARCHAR2 (20)  NOT NULL , 
     USUA_EMAIL              VARCHAR2 (100)  NOT NULL , 
     USUA_FECHANACIMIENTO    DATE , 
     USUA_DIRECCION          VARCHAR2 (200) , 
     USUA_TELEFONOPRICIPAL   VARCHAR2 (13) , 
     USUA_TELEFONOSECUNDARIO VARCHAR2 (13) , 
     USUA_REGISTRADOPOR      VARCHAR2 (30) , 
     USUA_FECHACAMBIO        TIMESTAMP 
    ) 
;

ALTER TABLE USUARIOS 
    ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( USUA_ID ) ;

CREATE TABLE VENTA 
    ( 
     VENT_ID            NUMBER (30)  NOT NULL , 
     MESA_ID            NUMBER (30)  NOT NULL , 
     VENT_FECHA         TIMESTAMP  NOT NULL , 
     VENT_ESTADO        VARCHAR2 (20)  NOT NULL , 
     VENT_TOTAL         NUMBER (15)  NOT NULL , 
     VENT_PROPINA       NUMBER (10)  NOT NULL , 
     VENT_REGISTRADOPOR VARCHAR2 (30) , 
     VENT_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE VENTA 
    ADD CONSTRAINT VENTA_PK PRIMARY KEY ( VENT_ID ) ;

CREATE TABLE ZONAHORARIA 
    ( 
     ZOHO_ID            NUMBER (30)  NOT NULL , 
     ZOHO_NOMBRE        VARCHAR2 (50)  NOT NULL , 
     ZOHO_DESCRIPCION   VARCHAR2 (100)  NOT NULL , 
     ZOHO_ABREVIATURA   VARCHAR2 (10)  NOT NULL , 
     ZOHO_OFFSETOUT     VARCHAR2 (10)  NOT NULL , 
     ZOHO_ESTADO        NUMBER  NOT NULL , 
     ZOHO_REGISTRADOPOR VARCHAR2 (30) , 
     ZOHO_FECHACAMBIO   TIMESTAMP 
    ) 
;

ALTER TABLE ZONAHORARIA 
    ADD CONSTRAINT ZONAHORARIA_PK PRIMARY KEY ( ZOHO_ID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE AUTENTICACION 
    ADD CONSTRAINT AUTENTICACION_TIPOAUTENTICACION_FK FOREIGN KEY 
    ( 
     TIAU_ID
    ) 
    REFERENCES TIPOAUTENTICACION 
    ( 
     TIAU_ID
    ) 
;

ALTER TABLE AUTENTICACION 
    ADD CONSTRAINT AUTENTICACION_USUARIOS_FK FOREIGN KEY 
    ( 
     USUA_ID
    ) 
    REFERENCES USUARIOS 
    ( 
     USUA_ID
    ) 
;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT CIUDAD_REGION_FK FOREIGN KEY 
    ( 
     REGI_ID
    ) 
    REFERENCES REGION 
    ( 
     REGI_ID
    ) 
;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT CIUDAD_ZONAHORARIA_FK FOREIGN KEY 
    ( 
     ZOHO_ID
    ) 
    REFERENCES ZONAHORARIA 
    ( 
     ZOHO_ID
    ) 
;

ALTER TABLE CUENTAVENTA 
    ADD CONSTRAINT CUENTAVENTA_VENTA_FK FOREIGN KEY 
    ( 
     VENT_ID
    ) 
    REFERENCES VENTA 
    ( 
     VENT_ID
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE "DETALLECUENTAVENTA " 
    ADD CONSTRAINT "DETALLECUENTAVENTA _CUENTAVENTA_FK" FOREIGN KEY 
    ( 
     CUVE_ID
    ) 
    REFERENCES CUENTAVENTA 
    ( 
     CUVE_ID
    ) 
;

ALTER TABLE "DETALLECUENTAVENTA " 
    ADD CONSTRAINT "DETALLECUENTAVENTA _PRECIO_FK" FOREIGN KEY 
    ( 
     PREC_ID
    ) 
    REFERENCES PRECIO 
    ( 
     PREC_ID
    ) 
;

ALTER TABLE EMPRESA 
    ADD CONSTRAINT EMPRESA_CIUDAD_FK FOREIGN KEY 
    ( 
     CIUD_ID
    ) 
    REFERENCES CIUDAD 
    ( 
     CIUD_ID
    ) 
;

ALTER TABLE EMPRESA 
    ADD CONSTRAINT EMPRESA_PAIS_FK FOREIGN KEY 
    ( 
     PAIS_IDTELEFONO
    ) 
    REFERENCES PAIS 
    ( 
     PAIS_ID
    ) 
;

ALTER TABLE EMPRESA 
    ADD CONSTRAINT EMPRESA_TIPO_IDENTIFICACION_FK FOREIGN KEY 
    ( 
     TIID_ID
    ) 
    REFERENCES TIPO_IDENTIFICACION 
    ( 
     TIID_ID
    ) 
;

ALTER TABLE EMPRESA 
    ADD CONSTRAINT EMPRESA_ZONAHORARIA_FK FOREIGN KEY 
    ( 
     ZOHO_ID
    ) 
    REFERENCES ZONAHORARIA 
    ( 
     ZOHO_ID
    ) 
;

ALTER TABLE INVENTARIO 
    ADD CONSTRAINT INVENTARIO_PRODUCTOS_FK FOREIGN KEY 
    ( 
     PROD_ID,
     SUCU_ID
    ) 
    REFERENCES PRODUCTOS 
    ( 
     PROD_ID,
     SUCU_ID
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE LOG_CREDENCIAL 
    ADD CONSTRAINT LOG_CREDENCIAL_TIPOAUTENTICACION_FK FOREIGN KEY 
    ( 
     TIAU_ID
    ) 
    REFERENCES TIPOAUTENTICACION 
    ( 
     TIAU_ID
    ) 
;

ALTER TABLE LOG_CREDENCIAL 
    ADD CONSTRAINT LOG_CREDENCIAL_USUARIOS_FK FOREIGN KEY 
    ( 
     USUA_ID
    ) 
    REFERENCES USUARIOS 
    ( 
     USUA_ID
    ) 
;

ALTER TABLE LOGIN_LOG 
    ADD CONSTRAINT LOGIN_LOG_USUARIOS_FK FOREIGN KEY 
    ( 
     USUA_ID
    ) 
    REFERENCES USUARIOS 
    ( 
     USUA_ID
    ) 
;

ALTER TABLE USUARIOROL 
    ADD CONSTRAINT MENUUSUARIO_ROLES_FK FOREIGN KEY 
    ( 
     USUA_ID
    ) 
    REFERENCES USUARIOS 
    ( 
     USUA_ID
    ) 
;

ALTER TABLE MESA 
    ADD CONSTRAINT MESA_SUCURSAL_FK FOREIGN KEY 
    ( 
     SUCU_ID
    ) 
    REFERENCES SUCURSAL 
    ( 
     SUCU_ID
    ) 
;

ALTER TABLE MOVIMIENTOS 
    ADD CONSTRAINT MOVIMIENTOS_PRODUCTOS_FK FOREIGN KEY 
    ( 
     PROD_ID,
     SUCU_ID
    ) 
    REFERENCES PRODUCTOS 
    ( 
     PROD_ID,
     SUCU_ID
    ) 
;

ALTER TABLE MOVIMIENTOS 
    ADD CONSTRAINT MOVIMIENTOS_TIPOMOVIMIENTO_FK FOREIGN KEY 
    ( 
     TIMO_ID
    ) 
    REFERENCES TIPOMOVIMIENTO 
    ( 
     TIMO_ID
    ) 
;

ALTER TABLE OPCIONMENU 
    ADD CONSTRAINT OPCIONMENU_MENUS_FK FOREIGN KEY 
    ( 
     MENU_ID
    ) 
    REFERENCES MENUS 
    ( 
     MENU_ID
    ) 
;

ALTER TABLE OPCIONMENU 
    ADD CONSTRAINT OPCIONMENU_ROLES_FK FOREIGN KEY 
    ( 
     ROLE_ID
    ) 
    REFERENCES ROLES 
    ( 
     ROLE_ID
    ) 
;

ALTER TABLE PAGOCUENTAVENTA 
    ADD CONSTRAINT PAGOCUENTAVENTA_CUENTAVENTA_FK FOREIGN KEY 
    ( 
     CUVE_ID
    ) 
    REFERENCES CUENTAVENTA 
    ( 
     CUVE_ID
    ) 
;

ALTER TABLE PAGOCUENTAVENTA 
    ADD CONSTRAINT PAGOCUENTAVENTA_MEDIOPAGO_FK FOREIGN KEY 
    ( 
     MEPA_ID
    ) 
    REFERENCES MEDIOPAGO 
    ( 
     MEPA_ID
    ) 
;

ALTER TABLE PAIS 
    ADD CONSTRAINT PAIS_ZONAHORARIA_FK FOREIGN KEY 
    ( 
     ZOHO_ID
    ) 
    REFERENCES ZONAHORARIA 
    ( 
     ZOHO_ID
    ) 
;

ALTER TABLE PRECIO 
    ADD CONSTRAINT PRECIO_PRODUCTOS_FK FOREIGN KEY 
    ( 
     PROD_ID,
     SUCU_ID
    ) 
    REFERENCES PRODUCTOS 
    ( 
     PROD_ID,
     SUCU_ID
    ) 
;

ALTER TABLE PRODUCTOS 
    ADD CONSTRAINT PRODUCTOS_MARCA_FK FOREIGN KEY 
    ( 
     MRCA_ID
    ) 
    REFERENCES MARCA 
    ( 
     MRCA_ID
    ) 
;

ALTER TABLE PRODUCTOS 
    ADD CONSTRAINT PRODUCTOS_SUCURSAL_FK FOREIGN KEY 
    ( 
     SUCU_ID
    ) 
    REFERENCES SUCURSAL 
    ( 
     SUCU_ID
    ) 
;

ALTER TABLE PRODUCTOS 
    ADD CONSTRAINT PRODUCTOS_TIPO_PRODUCTOS_FK FOREIGN KEY 
    ( 
     TPPR_ID
    ) 
    REFERENCES TIPO_PRODUCTOS 
    ( 
     TPPR_ID
    ) 
;

ALTER TABLE REGION 
    ADD CONSTRAINT REGION_PAIS_FK FOREIGN KEY 
    ( 
     PAIS_ID
    ) 
    REFERENCES PAIS 
    ( 
     PAIS_ID
    ) 
;

ALTER TABLE REGION 
    ADD CONSTRAINT REGION_ZONAHORARIA_FK FOREIGN KEY 
    ( 
     ZOHO_ID
    ) 
    REFERENCES ZONAHORARIA 
    ( 
     ZOHO_ID
    ) 
;

ALTER TABLE ROLES 
    ADD CONSTRAINT ROLES_TIPOUSUARIO_FK FOREIGN KEY 
    ( 
     TIUS_ID
    ) 
    REFERENCES TIPOUSUARIO 
    ( 
     TIUS_ID
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_CIUDAD_FK FOREIGN KEY 
    ( 
     CIUD_ID
    ) 
    REFERENCES CIUDAD 
    ( 
     CIUD_ID
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_EMPRESA_FK FOREIGN KEY 
    ( 
     EMPR_ID
    ) 
    REFERENCES EMPRESA 
    ( 
     EMPR_ID
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_MONEDA_FK FOREIGN KEY 
    ( 
     MONE_ID
    ) 
    REFERENCES MONEDA 
    ( 
     MONE_ID
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_PAIS_FK FOREIGN KEY 
    ( 
     PAIS_IDTELEFONO
    ) 
    REFERENCES PAIS 
    ( 
     PAIS_ID
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_ZONAHORARIA_FK FOREIGN KEY 
    ( 
     ZOHO_ID
    ) 
    REFERENCES ZONAHORARIA 
    ( 
     ZOHO_ID
    ) 
;

ALTER TABLE USUARIOROL 
    ADD CONSTRAINT USUARIOROL_ROLES_FK FOREIGN KEY 
    ( 
     ROLE_ID
    ) 
    REFERENCES ROLES 
    ( 
     ROLE_ID
    ) 
;

ALTER TABLE USUARIOS 
    ADD CONSTRAINT USUARIOS_CIUDAD_FK FOREIGN KEY 
    ( 
     CIUD_ID
    ) 
    REFERENCES CIUDAD 
    ( 
     CIUD_ID
    ) 
;

ALTER TABLE USUARIOS 
    ADD CONSTRAINT USUARIOS_EMPRESA_FK FOREIGN KEY 
    ( 
     EMPR_ID
    ) 
    REFERENCES EMPRESA 
    ( 
     EMPR_ID
    ) 
;

ALTER TABLE VENTA 
    ADD CONSTRAINT VENTA_MESA_FK FOREIGN KEY 
    ( 
     MESA_ID
    ) 
    REFERENCES MESA 
    ( 
     MESA_ID
    ) 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            32
-- CREATE INDEX                             3
-- ALTER TABLE                             71
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   5
-- WARNINGS                                 0
